[package]
name = "paimon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]  
reqwest = "0.11"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
url = "2.4.1"
is-url = "1.0.4"
lettre = "0.9.6"
lettre_email = "0.9.4"
mime = "0.3.13"
dotenv = "0.15"
figlet-rs = "0.1.3"
colored = "2.0"
dirs-next = "2.0"
clap = { version = "4.4.7", features = ["derive"] }
indicatif = "0.16"
uuid = { version = "0.8", features = ["v4"] }
zip = "0.5"
libflate = "0.1"
regex = "1.4"
once_cell = "1"
chrono = "0.4"
serde_json = "1.0"